---
#task file for repo_centos8

- name: Delete repo centos8 Stream
  file:
    path: /etc/yum.repos.d/*
    state: absent

- name: our repo centos8
  copy:
    src: local.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: '0644'
