- name: Install zabbix repo
  shell: dnf install https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent-6.0.5-1.el8.x86_64.rpm -y

- name: Install zabbix agent
  dnf:
    name:
      - zabbix-agent
    state: latest

- name: zabbix conf
  template:
    src: zabbix_agentd.conf.j2
    dest: '/etc/zabbix/zabbix_agentd.conf'
  become: true

- name: restart zabbix_agent
  service:
      name: zabbix-agent
      state: restarted
      enabled: true