- name: Install zabbix repo
  shell: dnf install https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent2-6.0.5-1.el8.x86_64.rpm -y 

- name: Install zabbix agent2
  dnf:
    name:
      - zabbix-agent2
    state: latest

- name: zabbix conf
  template:
    src: ./zabbix_agent2.conf.j2
    dest: '/etc/zabbix/zabbix_agent2.conf'

- name: restart zabbix_agent
  service:
      name: zabbix-agent2
      state: restarted
      enabled: true