---
- name: remove ssh pub key from .ssh/authorized_key
  hosts: all
  gather_facts: False

  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: centos
        state: absent
        key: "{{ lookup('file', '../ssh-keys/.pub') }}"
